### ISSUE TITLE
[ERROR] Halting process: ("Error on initialization") TProtocolException: Required field 'serialized_parts' is unset! 

### ISSUE THREAD

**Issue by salimane** [mesos/storm#116]
I'm getting some exceptions trying to start nimbus. I built the package using the current master branch ending up with ``storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.tgz``

Below is the full stacktrace

```
2016-03-26 00:26:49.796 b.s.u.Utils [INFO] Using defaults.yaml from resources
2016-03-26 00:26:49.893 b.s.u.Utils [INFO] Using storm.yaml from resources
2016-03-26 00:26:51.180 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2016-03-26 00:26:51.181 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:host.name=vagrant.myproject.com
2016-03-26 00:26:51.181 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.version=1.8.0_51
2016-03-26 00:26:51.181 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.vendor=Oracle Corporation
2016-03-26 00:26:51.182 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.home=/usr/java/jdk1.8.0_51/jre
2016-03-26 00:26:51.182 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.class.path=/opt/storm/lib/servlet-api-2.5.jar:/opt/storm/lib/kryo-2.21.jar:/opt/storm/lib/hadoop-auth-2.4.0.jar:/opt/storm/lib/slf4j-api-1.7.7.jar:/opt/storm/lib/log4j-slf4j-impl-2.1.jar:/opt/storm/lib/log4j-api-2.1.jar:/opt/storm/lib/minlog-1.2.jar:/opt/storm/lib/storm-core-0.10.0.jar:/opt/storm/lib/storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:/opt/storm/lib/log4j-core-2.1.jar:/opt/storm/lib/disruptor-2.10.4.jar:/opt/storm/lib/reflectasm-1.07-shaded.jar:/opt/storm/lib/clojure-1.6.0.jar:/opt/storm/lib/log4j-over-slf4j-1.6.6.jar:/opt/storm/lib/asm-4.0.jar:/opt/storm/conf
2016-03-26 00:26:51.182 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.library.path=/usr/local/lib:/opt/local/lib:/usr/lib
2016-03-26 00:26:51.183 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.io.tmpdir=/tmp
2016-03-26 00:26:51.183 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:java.compiler=<NA>
2016-03-26 00:26:51.183 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:os.name=Linux
2016-03-26 00:26:51.183 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:os.arch=amd64
2016-03-26 00:26:51.184 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:os.version=2.6.32-573.18.1.el6.x86_64
2016-03-26 00:26:51.184 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:user.name=storm
2016-03-26 00:26:51.184 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:user.home=/home/storm
2016-03-26 00:26:51.185 o.a.s.s.o.a.z.ZooKeeper [INFO] Client environment:user.dir=/opt/storm
2016-03-26 00:26:51.218 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2016-03-26 00:26:51.218 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:host.name=vagrant.myproject.com
2016-03-26 00:26:51.218 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.version=1.8.0_51
2016-03-26 00:26:51.218 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.vendor=Oracle Corporation
2016-03-26 00:26:51.219 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.home=/usr/java/jdk1.8.0_51/jre
2016-03-26 00:26:51.233 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.class.path=/opt/storm/lib/servlet-api-2.5.jar:/opt/storm/lib/kryo-2.21.jar:/opt/storm/lib/hadoop-auth-2.4.0.jar:/opt/storm/lib/slf4j-api-1.7.7.jar:/opt/storm/lib/log4j-slf4j-impl-2.1.jar:/opt/storm/lib/log4j-api-2.1.jar:/opt/storm/lib/minlog-1.2.jar:/opt/storm/lib/storm-core-0.10.0.jar:/opt/storm/lib/storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:/opt/storm/lib/log4j-core-2.1.jar:/opt/storm/lib/disruptor-2.10.4.jar:/opt/storm/lib/reflectasm-1.07-shaded.jar:/opt/storm/lib/clojure-1.6.0.jar:/opt/storm/lib/log4j-over-slf4j-1.6.6.jar:/opt/storm/lib/asm-4.0.jar:/opt/storm/conf
2016-03-26 00:26:51.234 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.library.path=/usr/local/lib:/opt/local/lib:/usr/lib
2016-03-26 00:26:51.234 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.io.tmpdir=/tmp
2016-03-26 00:26:51.234 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:java.compiler=<NA>
2016-03-26 00:26:51.234 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:os.name=Linux
2016-03-26 00:26:51.234 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:os.arch=amd64
2016-03-26 00:26:51.235 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:os.version=2.6.32-573.18.1.el6.x86_64
2016-03-26 00:26:51.235 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:user.name=storm
2016-03-26 00:26:51.235 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:user.home=/home/storm
2016-03-26 00:26:51.235 o.a.s.s.o.a.z.s.ZooKeeperServer [INFO] Server environment:user.dir=/opt/storm
2016-03-26 00:26:51.430 b.s.u.Utils [INFO] Using defaults.yaml from resources
2016-03-26 00:26:51.443 b.s.u.Utils [INFO] Using storm.yaml from resources
2016-03-26 00:26:51.477 s.m.LocalFileServer [INFO] Starting local file server on port: 8699
2016-03-26 00:26:51.484 o.m.s.log [INFO] Logging to org.apache.logging.slf4j.Log4jLogger@5a8ba37c via org.mortbay.shaded.log.Slf4jLog
2016-03-26 00:26:51.541 o.m.s.log [INFO] jetty-6.1.x
2016-03-26 00:26:51.556 o.m.s.log [INFO] Started [SocketConnector@0.0.0.0:8699, null]
2016-03-26 00:26:51.565 o.m.s.log [INFO] Started [SelectChannelConnector@0.0.0.0:34680, null]
2016-03-26 00:26:51.567 s.m.MesosNimbus [INFO] Started HTTP server from which config for the MesosSupervisor's may be fetched. URL: http://vagrant.myproject.com:8699/generated-conf
2016-03-26 00:26:51.746 s.m.MesosNimbus [ERROR] Failed to prepare scheduler
java.lang.RuntimeException: java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at backtype.storm.utils.LocalState.partialSnapshot(LocalState.java:118) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.get(LocalState.java:126) ~[storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.shims.LocalStateShim.get(LocalStateShim.java:40) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createFrameworkBuilder(MesosNimbus.java:789) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createMesosDriver(MesosNimbus.java:328) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.prepare(MesosNimbus.java:173) [storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) [clojure-1.6.0.jar:?]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$fn__6583$exec_fn__1236__auto____6584.invoke(nimbus.clj:1011) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) [clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) [clojure-1.6.0.jar:?]
	at clojure.core$apply.invoke(core.clj:624) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$fn__6583$service_handler__6703.doInvoke(nimbus.clj:1010) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1368) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1399) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.nimbus.launch(Unknown Source) [storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.MesosNimbus.main(MesosNimbus.java:145) [storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
Caused by: java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at backtype.storm.utils.LocalState.partialDeserializeLatestVersion(LocalState.java:106) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.partialSnapshot(LocalState.java:114) ~[storm-core-0.10.0.jar:0.10.0]
	... 21 more
Caused by: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at backtype.storm.generated.LocalStateData.validate(LocalStateData.java:336) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.LocalStateData$LocalStateDataStandardScheme.read(LocalStateData.java:403) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.LocalStateData$LocalStateDataStandardScheme.read(LocalStateData.java:364) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.LocalStateData.read(LocalStateData.java:310) ~[storm-core-0.10.0.jar:0.10.0]
	at org.apache.thrift7.TDeserializer.deserialize(TDeserializer.java:81) ~[storm-core-0.10.0.jar:0.10.0]
	at org.apache.thrift7.TDeserializer.deserialize(TDeserializer.java:67) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.partialDeserializeLatestVersion(LocalState.java:100) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.partialSnapshot(LocalState.java:114) ~[storm-core-0.10.0.jar:0.10.0]
	... 21 more
2016-03-26 00:26:51.758 b.s.d.nimbus [ERROR] Error on initialization of server service-handler
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at storm.mesos.MesosNimbus.prepare(MesosNimbus.java:185) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$fn__6583$exec_fn__1236__auto____6584.invoke(nimbus.clj:1011) ~[storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.6.0.jar:?]
	at clojure.core$apply.invoke(core.clj:624) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$fn__6583$service_handler__6703.doInvoke(nimbus.clj:1010) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1368) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1399) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.nimbus.launch(Unknown Source) [storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.MesosNimbus.main(MesosNimbus.java:145) [storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at backtype.storm.utils.LocalState.partialSnapshot(LocalState.java:118) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.get(LocalState.java:126) ~[storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.shims.LocalStateShim.get(LocalStateShim.java:40) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createFrameworkBuilder(MesosNimbus.java:789) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createMesosDriver(MesosNimbus.java:328) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.prepare(MesosNimbus.java:173) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	... 16 more
Caused by: java.lang.RuntimeException: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at backtype.storm.utils.LocalState.partialDeserializeLatestVersion(LocalState.java:106) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.partialSnapshot(LocalState.java:114) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.get(LocalState.java:126) ~[storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.shims.LocalStateShim.get(LocalStateShim.java:40) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createFrameworkBuilder(MesosNimbus.java:789) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createMesosDriver(MesosNimbus.java:328) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.prepare(MesosNimbus.java:173) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	... 16 more
Caused by: org.apache.thrift7.protocol.TProtocolException: Required field 'serialized_parts' is unset! Struct:LocalStateData(serialized_parts:null)
	at backtype.storm.generated.LocalStateData.validate(LocalStateData.java:336) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.LocalStateData$LocalStateDataStandardScheme.read(LocalStateData.java:403) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.LocalStateData$LocalStateDataStandardScheme.read(LocalStateData.java:364) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.LocalStateData.read(LocalStateData.java:310) ~[storm-core-0.10.0.jar:0.10.0]
	at org.apache.thrift7.TDeserializer.deserialize(TDeserializer.java:81) ~[storm-core-0.10.0.jar:0.10.0]
	at org.apache.thrift7.TDeserializer.deserialize(TDeserializer.java:67) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.partialDeserializeLatestVersion(LocalState.java:100) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.partialSnapshot(LocalState.java:114) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.LocalState.get(LocalState.java:126) ~[storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.shims.LocalStateShim.get(LocalStateShim.java:40) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createFrameworkBuilder(MesosNimbus.java:789) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.createMesosDriver(MesosNimbus.java:328) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	at storm.mesos.MesosNimbus.prepare(MesosNimbus.java:173) ~[storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
	... 16 more
2016-03-26 00:26:51.766 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:336) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$fn__6583$service_handler__6703.doInvoke(nimbus.clj:1010) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:421) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.nimbus$launch_server_BANG_.invoke(nimbus.clj:1368) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.nimbus$_launch.invoke(nimbus.clj:1399) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.nimbus.launch(Unknown Source) [storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.MesosNimbus.main(MesosNimbus.java:145) [storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.28.0.jar:?]
```

**Comment by erikdw** [comment]
Unfortunately, I cannot reproduce this.  I used the vagrant setup in the repo, and built the package like so:
```
STORM_RELEASE=0.10.0 MESOS_RELEASE=0.28.0 bin/build-release.sh
```

I also updated the `Vagrantfile` to install mesos-0.28.0:
```
0 23:21:31 eweathers@GM16981(...d-party/storm-mesos) [master] % gd Vagrantfile 
diff --git Vagrantfile Vagrantfile
index 1a14fba..8eecef0 100755
--- Vagrantfile
+++ Vagrantfile
@@ -41,7 +41,7 @@ echo "Installing aria2..."
 apt-get -o Acquire::http::Timeout=1 -o Acquire::ftp::Timeout=1 -y install aria2
 
 echo "${PREFIX}Installing mesos ..."
-apt-get -o Acquire::http::Timeout=1 -o Acquire::ftp::Timeout=1 -y install mesos=0.25.0-0.2.70.ubuntu1404
+apt-get -o Acquire::http::Timeout=1 -o Acquire::ftp::Timeout=1 -y install mesos=0.28.0-2.0.16.ubuntu1404
 echo "Done"
```

Here's my guess about what you are facing:  perhaps you have changed the storm version from 0.9 to 0.10.0, and you didn't wipe out the storm-local dir where the LocalState file is stored.

**Comment by erikdw** [comment]
Yeah, I like my guess:
* [storm-0.10.0's LocalState *_does_* have a reference "serialized_parts"](https://github.com/apache/storm/blob/v0.10.0/storm-core/src/jvm/backtype/storm/utils/LocalState.java)
* [storm-0.9.6 does _*NOT*_](https://github.com/apache/storm/blob/v0.9.6/storm-core/src/jvm/backtype/storm/utils/LocalState.java)

**Comment by salimane** [comment]
@erikdw , you were right. Thanks

**Comment by erikdw** [comment]
@salimane : ah, great to here!
