### ISSUE TITLE
ConcurrentHashMap serialization/type issue

### ISSUE THREAD

**Issue by drewrobb** [mesos/storm#119]
Building against current master I'm getting an exception. 
@erikdw the exception is in mk-supervisor and I think is introduced by https://github.com/mesos/storm/pull/106 from using ConcurrentHashMap. I don't know if java 8 is officially supported, but internally we are using it. What I believe to be the issue is described a bit here: https://gist.github.com/AlainODea/1375759b8720a3f9f094

```
2016-03-29 23:39:03.006 b.s.d.supervisor [ERROR] Error on initialization of server mk-supervisor
java.lang.ClassCastException: java.util.concurrent.ConcurrentHashMap$KeySetView cannot be cast to java.lang.Number
	at clojure.lang.RT.longCast(RT.java:1151) ~[clojure-1.6.0.jar:?]
	at clojure.core$long.invoke(core.clj:3195) ~[clojure-1.6.0.jar:?]
	at clojure.core$map$fn__4245.invoke(core.clj:2557) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.count(LazySeq.java:65) ~[clojure-1.6.0.jar:?]
	at clojure.lang.LazySeq.size(LazySeq.java:167) ~[clojure-1.6.0.jar:?]
	at backtype.storm.generated.SupervisorInfo$SupervisorInfoStandardScheme.write(SupervisorInfo.java:1108) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.SupervisorInfo$SupervisorInfoStandardScheme.write(SupervisorInfo.java:954) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.generated.SupervisorInfo.write(SupervisorInfo.java:838) ~[storm-core-0.10.0.jar:0.10.0]
	at org.apache.thrift7.TSerializer.serialize(TSerializer.java:79) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.serialization.GzipThriftSerializationDelegate.serialize(GzipThriftSerializationDelegate.java:41) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.utils.Utils.serialize(Utils.java:76) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.cluster$mk_storm_cluster_state$reify__5120.supervisor_heartbeat_BANG_(cluster.clj:403) ~[storm-core-0.10.0.jar:0.10.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66-internal]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.6.0.jar:?]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.supervisor$fn__7682$exec_fn__1236__auto____7683$heartbeat_fn__7685.invoke(supervisor.clj:514) ~[storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.supervisor$fn__7682$exec_fn__1236__auto____7683.invoke(supervisor.clj:515) ~[storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.AFn.applyToHelper(AFn.java:160) ~[clojure-1.6.0.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.6.0.jar:?]
	at clojure.core$apply.invoke(core.clj:624) ~[clojure-1.6.0.jar:?]
	at backtype.storm.daemon.supervisor$fn__7682$mk_supervisor__7709.doInvoke(supervisor.clj:495) [storm-core-0.10.0.jar:0.10.0]
	at clojure.lang.RestFn.invoke(RestFn.java:436) [clojure-1.6.0.jar:?]
	at backtype.storm.daemon.supervisor$_launch.invoke(supervisor.clj:785) [storm-core-0.10.0.jar:0.10.0]
	at backtype.storm.daemon.supervisor.launch(Unknown Source) [storm-core-0.10.0.jar:0.10.0]
	at storm.mesos.MesosSupervisor.main(MesosSupervisor.java:65) [storm-mesos-0.1.0-SNAPSHOT-storm0.10.0-mesos0.27.1.jar:?]
2016-03-29 23:39:03.015 b.s.util [ERROR] Halting process: ("Error on initialization")
```

**Comment by erikdw** [comment]
hey @drewrobb : sorry that #106 broke you!  I've been building with JDK 7, but running with JRE 8, so it seems that we're talking about building with JDK 8.  The link you posted seems very useful (though it's got a repeated typo of Convariance instead of Covariance).  Let me look into how best to handle this.

BTW, I also saw an issue with serialization with #106 , and [https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/storm/src/main/storm/mesos/TaskAssignments.java#L60-L64](I worked around it with these lines).  The exception looked like the following:

```
2016-03-16T09:06:08.248+0000 b.s.d.supervisor [ERROR] Error on initialization of server mk-supervisor
java.lang.RuntimeException: java.io.NotSerializableException: storm.mesos.TaskAssignments$AssignmentInfo
	at backtype.storm.serialization.DefaultSerializationDelegate.serialize(DefaultSerializationDelegate.java:43) ~[storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.utils.Utils.serialize(Utils.java:85) ~[storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.cluster$mk_storm_cluster_state$reify__2370.supervisor_heartbeat_BANG_(cluster.clj:358) ~[storm-core-0.9.6.jar:0.9.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.5.1.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$exec_fn__1104__auto____5115$heartbeat_fn__5117.invoke(supervisor.clj:423) ~[storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor$fn__5114$exec_fn__1104__auto____5115.invoke(supervisor.clj:424) ~[storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.AFn.applyToHelper(AFn.java:167) ~[clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) ~[clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$mk_supervisor__5140.doInvoke(supervisor.clj:405) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:436) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$_launch.invoke(supervisor.clj:630) [storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor.launch(Unknown Source) [storm-core-0.9.6.jar:0.9.6]
	at storm.mesos.MesosSupervisor.main(MesosSupervisor.java:64) [storm-mesos-0.1.0-SNAPSHOT-storm0.9.6-mesos0.27.0.jar:na]
Caused by: java.io.NotSerializableException: storm.mesos.TaskAssignments$AssignmentInfo
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_74]
	at java.util.concurrent.ConcurrentHashMap.writeObject(ConcurrentHashMap.java:1413) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1378) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_74]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_74]
	at backtype.storm.serialization.DefaultSerializationDelegate.serialize(DefaultSerializationDelegate.java:39) ~[storm-core-0.9.6.jar:0.9.6]
	... 18 common frames omitted
2016-03-16T09:06:08.251+0000 b.s.util [ERROR] Halting process: ("Error on initialization")
java.lang.RuntimeException: ("Error on initialization")
	at backtype.storm.util$exit_process_BANG_.doInvoke(util.clj:325) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$mk_supervisor__5140.doInvoke(supervisor.clj:405) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:436) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$_launch.invoke(supervisor.clj:630) [storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor.launch(Unknown Source) [storm-core-0.9.6.jar:0.9.6]
	at storm.mesos.MesosSupervisor.main(MesosSupervisor.java:64) [storm-mesos-0.1.0-SNAPSHOT-storm0.9.6-mesos0.27.0.jar:na]
```

**Comment by erikdw** [comment]
(BTW, I'm also unsure _why_ storm would want to serialize the entire Supervisor object as it heartbeats, perhaps it *does* have some merit that I'm not seeing.)

**Comment by drewrobb** [comment]
Strange, looking at your code and reading the link that I posted it seems you are doing things correctly by casting the type to `Set<Integer>`. Also strange is that the pom.xml looks to set to build for java 7 right? https://github.com/mesos/storm/blob/master/pom.xml#L29. Maybe there is some other cause of my error.

**Comment by erikdw** [comment]
I'm not sure that [those 2 lines](https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/pom.xml#L28-L29) have any effect actually, since they aren't referred to later in any of the `pom.xml` files, and we aren't using some ["basepom"](https://github.com/basepom/basepom) for this project.

The [`java.abi` setting](https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/pom.xml#L27) however _does_ [appear to be used](https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/storm/pom.xml#L48-L49), though it also appears [redundant with the following settings:
* https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/storm/pom.xml#L26
* https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/storm-shim-9x/pom.xml#L26
* https://github.com/mesos/storm/blob/b6f232a5edfae4b0be7b747731a46bdd4ac2567f/storm-shim-10x/pom.xml#L27

So... we have some cleaning up to do of our `pom.xml` files it seems.  And I'm still unsure what behavior we should be expecting w.r.t. target java version.  And your issue appears a legitimate issue to me.  So I need to spend some time on this still.

**Comment by lfundaro** [comment]
I think I might have stumbled upon into a similar/related issue. I'm getting this with the latest docker image build, which is using storm=0.9.6 and mesos=0.27.0. This happened while trying to run the example WordCountTopology. 

```
2016-03-31T14:23:31.410+0000 b.s.d.supervisor [ERROR] Error on initialization of server mk-supervisor
java.lang.RuntimeException: java.io.NotSerializableException: java.util.concurrent.ConcurrentHashMap$KeySet
	at backtype.storm.serialization.DefaultSerializationDelegate.serialize(DefaultSerializationDelegate.java:43) ~[storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.utils.Utils.serialize(Utils.java:85) ~[storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.cluster$mk_storm_cluster_state$reify__2370.supervisor_heartbeat_BANG_(cluster.clj:358) ~[storm-core-0.9.6.jar:0.9.6]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_95]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_95]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_95]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.5.1.jar:na]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$exec_fn__1104__auto____5115$heartbeat_fn__5117.invoke(supervisor.clj:423) ~[storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor$fn__5114$exec_fn__1104__auto____5115.invoke(supervisor.clj:424) ~[storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.AFn.applyToHelper(AFn.java:167) ~[clojure-1.5.1.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:151) ~[clojure-1.5.1.jar:na]
	at clojure.core$apply.invoke(core.clj:617) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$fn__5114$mk_supervisor__5140.doInvoke(supervisor.clj:405) [storm-core-0.9.6.jar:0.9.6]
	at clojure.lang.RestFn.invoke(RestFn.java:436) [clojure-1.5.1.jar:na]
	at backtype.storm.daemon.supervisor$_launch.invoke(supervisor.clj:630) [storm-core-0.9.6.jar:0.9.6]
	at backtype.storm.daemon.supervisor.launch(Unknown Source) [storm-core-0.9.6.jar:0.9.6]
	at storm.mesos.MesosSupervisor.main(MesosSupervisor.java:65) [storm-mesos-0.1.0-SNAPSHOT-storm0.9.6-mesos0.27.0.jar:na]
Caused by: java.io.NotSerializableException: java.util.concurrent.ConcurrentHashMap$KeySet
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1377) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1173) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177) ~[na:1.7.0_95]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347) ~[na:1.7.0_95]
	at backtype.storm.serialization.DefaultSerializationDelegate.serialize(DefaultSerializationDelegate.java:39) ~[storm-core-0.9.6.jar:0.9.6]
	... 18 common frames omitted
2016-03-31T14:23:31.424+0000 b.s.util [ERROR] Halting process: ("Error on initialization")
```

**Comment by lfundaro** [comment]
Quick update. In my case I'm using java7

**Comment by erikdw** [comment]
@lfundaro : thanks for the extra info.  I haven't been able to reproduce these issues with storm-0.9.6, despite compiling with jdk 1.8 and running on jre 1.8.  Similarly, I compiled with jdk 1.7 and ran on jre 1.8 and had no issues.  Maybe if I used jre 1.7 it would reproduce for me. Or maybe if I tried storm-0.10.0. Sigh.

So... after looking further into the Clojure docs, I believe the problem is *really* misuse of `PersistentVector.create()`.  I have proposed a change in #121 which I hope will fix these issues for you and @drewrobb .

Can you please test and verify that with the change in #121 that your problems are gone?

Thanks!!

**Comment by lfundaro** [comment]
@erikdw  I just tested PR #121 and it solves the problem ! 😄  
👏  thank you !

**Comment by drewrobb** [comment]
I also can confirm that #121 fixes this. Thank you @erikdw

**Comment by erikdw** [comment]
thanks for confirming @lfundaro & @drewrobb!   I'm going to merge in #121 now.

**Comment by erikdw** [comment]
thanks for confirming @lfundaro & @drewrobb!   I'm going to merge in #121 now.
