### ISSUE TITLE
Connection Refused: storm-mesos

### ISSUE THREAD

**Issue by ramukima** [mesos/storm#21]
Trying to follow this - https://mesosphere.com/docs/tutorials/run-storm-on-mesos/#step-1

./bin/storm-mesos nimbus

```
2014-11-17 16:33:52 o.a.z.ZooKeeper [INFO] Initiating client connection, connectString=localhost:2181 sessionTimeout=20000 watcher=com.netflix.curator.ConnectionState@5b4aa17
2014-11-17 16:33:52 o.a.z.ClientCnxn [INFO] Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181
2014-11-17 16:33:52 o.a.z.ClientCnxn [WARN] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.7.0_67]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739) ~[na:1.7.0_67]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1119) ~[zookeeper-3.3.3.jar:3.3.3-1073969]
2014-11-17 16:33:53 o.a.z.ClientCnxn [INFO] Opening socket connection to server localhost/127.0.0.1:2181
2014-11-17 16:33:53 o.a.z.ClientCnxn [WARN] Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
```

```
bash-3.2$ cat conf/storm.yaml 
# Please change these for your cluster 
# to reflect your cluster settings
# -----------------------------------------------------------
mesos.master.url: "localhost:5050"
storm.zookeeper.servers:
    - "localhost"
nimbus.host: "localhost"
# -----------------------------------------------------------

# You should not need to change anything below this line
#--------------------------------------------------------

# Use the public Mesosphere Storm build
# Please note that it won't work with other distributions
mesos.executor.uri: "http://downloads.mesosphere.io/storm/storm-mesos-0.9.tgz"

# Use Netty to avoid ZMQ dependencies
storm.messaging.transport: "backtype.storm.messaging.netty.Context"

storm.local.dir: "storm-local"

mesos.framework.role: "*"
mesos.framework.checkpoint: false

#mesos.allowed.hosts:
#  - host1
#mesos.disallowed.hosts:
#  - host1
bash-3.2$ 
```

Note that mesos primary is running at port 5050 on the localhost.

Tried couple of things to get this to work, but no success...

export JAVA_OPTS="-Djava.net.preferIPv4Stack=true"

**Comment by chengweiv5** [comment]
```
storm.zookeeper.servers:
    - "localhost"
```
Did you have zookeeper running on your 'localhost'?

**Comment by erikdw** [comment]
Yep, this problem is that there is no ZooKeeper available.
