### ISSUE TITLE
Storm v1.1.0+ breaks storm-mesos

### ISSUE THREAD

**Issue by erikdw** [mesos/storm#214]
This problem looks to be very tricky indeed.  I will add details later, for now you can read about the change that broke us in a [comment I added to STORM-2126](https://issues.apache.org/jira/browse/STORM-2126?focusedCommentId=16136150&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16136150).

**Comment by mayankdhiman27** [comment]
hi @erikdw ,
I am using storm 1.2.1, and I am getting exception:
`3488 [main] WARN  o.a.s.u.Utils - STORM-VERSION new 1.2.1 old 1.2.1
3505 [main] WARN  o.a.s.d.nimbus - Topology submission exception. (topology name='streamline-1-test-app') #error {
 :cause nil
 :via
 [{:type org.apache.storm.generated.InvalidTopologyException
   :message nil
   :at [org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799$fn__10800 invoke nimbus.clj 1690]}]
 :trace
 [[org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799$fn__10800 invoke nimbus.clj 1690]
  [org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799 submitTopologyWithOpts nimbus.clj 1687]
  [org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799 submitTopology nimbus.clj 1774]
  [sun.reflect.NativeMethodAccessorImpl invoke0 NativeMethodAccessorImpl.java -2]
  [sun.reflect.NativeMethodAccessorImpl invoke NativeMethodAccessorImpl.java 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke DelegatingMethodAccessorImpl.java 43]
  [java.lang.reflect.Method invoke Method.java 498]
  [clojure.lang.Reflector invokeMatchingMethod Reflector.java 93]
  [clojure.lang.Reflector invokeInstanceMethod Reflector.java 28]
  [org.apache.storm.testing$submit_local_topology invoke testing.clj 310]
  [org.apache.storm.LocalCluster$_submitTopology invoke LocalCluster.clj 49]
  [org.apache.storm.LocalCluster submitTopology nil -1]
  [org.apache.storm.flux.Flux runCli Flux.java 212]
  [org.apache.storm.flux.Flux main Flux.java 103]]}
3505 [main] ERROR o.a.s.s.o.a.z.s.NIOServerCnxnFactory - Thread Thread[main,5,main] died
org.apache.storm.generated.InvalidTopologyException: null
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799$fn__10800.invoke(nimbus.clj:1690) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799.submitTopologyWithOpts(nimbus.clj:1687) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.daemon.nimbus$mk_reified_nimbus$reify__10799.submitTopology(nimbus.clj:1774) ~[storm-core-1.2.1.jar:1.2.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93) ~[clojure-1.7.0.jar:?]
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.testing$submit_local_topology.invoke(testing.clj:310) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.LocalCluster$_submitTopology.invoke(LocalCluster.clj:49) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.LocalCluster.submitTopology(Unknown Source) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.flux.Flux.runCli(Flux.java:212) ~[streamline-runtime-storm-0.6.0-SNAPSHOT.jar:0.6.0-SNAPSHOT]
	at org.apache.storm.flux.Flux.main(Flux.java:103) ~[streamline-runtime-storm-0.6.0-SNAPSHOT.jar:0.6.0-SNAPSHOT]`
	
Trying to submit one topology from streamline and getting this error.

**Comment by erikdw** [comment]
hi @mayankdhiman27 : AFAIK you won't be able to use Storm 1.1+ with this project.  Note that [mesos itself is also basically deprecated](https://thenewstack.io/apache-mesos-narrowly-avoids-a-move-to-the-attic-for-now/), so you should probably be looking to move to another project like k8s.
